swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert(document.domain)//
info:
  version: "1.0.0"
  title: XSS img test
  description: <h1><a href=https://evil.com>CLick Me</h1> <img src=https://academy.avast.com/hubfs/New_Avast_Academy/Hackers/Hacker-Hero-a1.png onclick="alert(2)" onerror="alert(3)">
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              script:
                type: string
                default: "<script nonce='TkB4bEAwTzk='>alert('XSS')</script>"
